// Generated by https://quicktype.io

export interface MKIcons {
    common: { [key: string]: string };
    "en-CA": ArQA;
    "en-QA": ArQA;
    "ar-QA": ArQA;
    "en-US": ArQA;
    "fr-CA": FrCA;
    "es-CL": ArQA;
    "hu-HU": ArQA;
}

export interface ArQA {
}

export interface FrCA {
    source_vod: string;
    source_ppv: string;
    source_live: string;
    source_dvr: string;
    new: string;
    badge_upcoming: string;
    badge_restart: string;
}
