export const pbr = {
    RestrictionsType: {
        FWD_BLOCKED: "fwd_blocked",
        RECORD_BLOCKED: "record_blocked",
        OUTOFHOME_BLOCKED: "out_of_home_blocked",
        RWD_BLOCKED: "rwd_blocked",
        RECENTLYAIRED_BLOCKED: "recentlyAired_blocked",
        TIMESHIFT_BLOCKED: "timeshift_blocked",
        CATCHUP_BLOCKED: "catchup_blocked",
        JAILBROKEN_BLOCKED: "jailbroken_blocked",
        PAUSE_RESUME_BLOCKED: "pause_resume_blocked",
        SEEK_SKIP_BLOCKED: "seek_skip_blocked",
        SEEK_SKIP_FWD_BLOCKED: "seek_skip_fwd_blocked",
        SEEK_SKIP_RWD_BLOCKED: "seek_skip_rwd_blocked",
        RESTART_NOW_BLOCKED: "restart_now_blocked",
        OH: "oh", // out of home blocked
        FW: "fw", // forward blocked
        RW: "rw", // rewind blocked
        PR: "pr", // pause resume blocked
        SS: "ss", // seek skip blocked NOTE: to be deprecated
        SF: "sf", // seek skip forward blocked
        SR: "sr", // seek skip rewind blocked
        RN: "rn", // restart now blocked
        CT: "ct", // catchup allowed
        SB: "sb", // recording network share blocked
        NB: "nb", // recording network blocked
        LB: "lb", // recording local blocked
        TS: "ts", // timeshift blocked
        RA: "ra", // recently aired blocked
        CU: "cu", // catch up blocked
        HI: "hi", // HDMI blocked
        AP: "ap", // Airplay blocked
        DOWNLOAD_BLOCKED: "download_blocked",
    },
    AbbreviatedRestrictions: {
        oh: "out_of_home_blocked",
        fw: "fwd_blocked",
        rw: "rwd_blocked",
        pr: "pause_resume_blocked",
        ss: "seek_skip_blocked",
        sf: "seek_skip_fwd_blocked",
        sr: "seek_skip_rwd_blocked",
        rn: "restart_now_blocked",
        sb: "sb",
        nb: "record_blocked",
        lb: "lb",
        ts: "timeshift_blocked",
        ra: "recentlyAired_blocked",
        cu: "catchup_blocked",
    },
};

export enum RestrictionValue {
    Yes = "Yes",
    No = "No",
    DoNotKnow = "DoNotKnow",
}

export const fontIconsObject = {
    en: "locale_en",
    UHD: "quality_4k",
    HD: "quality_hd",
    SD: "quality_sd",
    Dolby: "quality_dolby",
    ClosedCaptioned: "closed_captions_badge",
    AudioDescription: "descriptive_audio",
};

export const transactionType = {
    PURCHASE: "Purchase",
    RENT: "Rent",
    SUBSCRIBE: "Subscription",
};

export const orderedQualityLevels = {
    UHD: 0,
    ReachUHD: 1,
    HD: 2,
    ReachHD: 3,
    SD: 4,
    ReachSD: 5,
};

export const generalizeQualityLevels = {
    ReachUHD: "UHD",
    ReachHD: "HD",
    ReachSD: "SD",
};

export const encodings = {
    Hls: 1,
    SmoothStreaming: 1,
    Jitp: 1,
};

export const AspectRatio = {
    "2x3": "2x3",
    "16x9": "16x9",
    "3x4": "3x4",
};

export const defaultBackgroundImage = {
    uri: "res://drawable/default/DefaultBackground.png",
};

export const placeholder16x9Image = {
    uri: "res://drawable/default/PlaceHolder.png",
};

export const placeholder2x3Image = {
    uri: "res://drawable/default/PlaceHolder2x3.png",
};

export const placeholder3x4Image = {
    uri: "res://drawable/default/PlaceHolder3x4.png",
};

export const hourGlassImage = {
    uri: "res://drawable/default/Hour-Glass.png",
};

export const networkLogoPlaceholder = {
    uri: "res://drawable/default/NetworkLogoPlaceholder.png",
};

export const assetTypeObject: { [key: string]: number } = {
    PROGRAM: 0,
    SEASON: 2,
    SERIES: 2,
    EPISODE: 2,
    PERSON: 10,
};

export const languageKey = {
    language: "Language|",
};

export enum ContentType {
    PROGRAM = "PROGRAM",
    GENERIC = "GENERIC",
    SERIES = "SERIES",
    EPISODE = "EPISODE",
}

export const itemTypeString: { [key: string]: string } = {
    0: "Program",
    2: "Series",
};

export const imageMappingObject: { [key: string]: string } = {
    "16x9/KeyArt": "16x9/keyartlarge.jpg",
    "16x9/Poster": "16x9/posterlarge.jpg",
    "2x3/KeyArt": "2x3/keyartlarge.jpg",
    "2x3/Poster": "2x3/posterlarge.jpg",
    "3x4/KeyArt": "3x4/keyartlarge.jpg",
    "3x4/Poster": "3x4/posterlarge.jpg",
};

export const browseType = {
    favorites: "favorites",
    libraries: "libraries",
    browsepromotions: "browsepromotions",
    browsemovies: "browsemovies",
    browsetv: "browsetv",
    restartTv: "restartTv",
    browsepackages: "browsepackages",
    browsemoviesandtv: "browsemoviesandtv",
    browserecommendations: "browserecommendations",
    browsemixedrecommendations: "browsemixedrecommendations",
    favoriteschannel: "favoriteschannel",
    browsedvrtvshows: "browsedvrtvshows",
    browsedvrmovies: "browsedvrmovies",
    browsesearch: "browsesearch",
};

export const feedBaseURI = {
    discovery: new RegExp(/^udl:\/\/discovery\/(\S)/),
    subscriber: new RegExp(/^udl:\/\/subscriber\/(\S)/),
    catchup: new RegExp(/^udl:\/\/live\/feeds\/catchup(\S)/),
};

export const showcardLayout = {
    "1:1": "Layout1x1",
    "2:3": "Layout2x3",
    "3:2": "Layout3x2",
    "4:3": "Layout4x3",
    "3:4": "Layout3x4",
    "16:9": "Layout16x9",
    Layout1x1: "1:1",
    Layout2x3: "2:3",
    Layout3x2: "3:2",
    Layout4x3: "4:3",
    Layout3x4: "3:4",
    Layout16x9: "16:9",
};

export const imageType = {
    "1x1/Poster": "1x1/Poster",
    "2x3/KeyArt": "2x3/KeyArt",
    "2x3/Poster": "2x3/Poster",
    "3x2/KeyArt": "3x2/KeyArt",
    "3x4/KeyArt": "3x4/KeyArt",
    "3x4/Poster": "3x4/Poster",
    "4x3/KeyArt": "4x3/KeyArt",
    "4x3/Poster": "4x3/Poster",
    "16x9/KeyArt": "16x9/KeyArt",
    "16x9/Poster": "16x9/Poster",
    KeyArtLandscape: "KeyArtLandscape",
    PosterLandscape: "PosterLandscape",
};

export const networkImageType = {
    TenFootSmall: "TenFootSmall",
    TenFootLarge: "TenFootLarge",
    TwoFootLarge: "TwoFootLarge",
    TwoFootSmall: "TwoFootSmall",
    OneFootLarge: "OneFootLarge",
    OneFootSmall: "OneFootSmall",
};

export const galleryFilter = {
    SORTBY_KEY: "SortBy",
    SHOWTYPE_KEY: "ShowType",
    GENRE_KEY: "Genre",
    LANGUAGE_KEY: "Language",
    LICENSEWINDOW_KEY: "LicenseWindow",
    PRICE_KEY: "Price",
    QUALITYLEVEL_KEY: "QualityLevel",
    OFFERTYPE_KEY: "OfferType",
    RESTRICTIONS_KEY: "Restrictions",
};

export enum playBackMode {
    VOD,
    LIVE,
}

export enum sourceTypeString {
    "LIVE" = "LIVE",
    "CATCHUP" = "CATCHUP",
    "DVR" = "DVR",
    "VOD" = "VOD",
    "UPCOMING" = "UPCOMING",
    "PERSON" = "PERSON",
}

export enum bookmarkType {
    "Catchup" = "Catchup",
    "Recording" = "Recording",
    "Video" = "Video",
}

export enum ControlEvents {
    "ArrowUp" = "ArrowUp",
    "ArrowDown" = "ArrowDown",
    "ArrowLeft" = "ArrowLeft",
    "ArrowRight" = "ArrowRight",
    "Enter" = "Enter",
    "MediaPlayPause" = "MediaPlayPause",
    "MediaPlay" = "MediaPlay",
    "Pause" = "Pause",
    "SiriRemoteClickUp" = "SiriRemoteClickUp",
}

export enum PlayerState {
    "Uninitialized" = "Uninitialized",
    "Initialized" = "Initialized",
    "Loading" = "Loading",
    "Loaded" = "Loaded",
    "Paused" = "Paused",
    "Playing" = "Playing",
    "Complete" = "Complete",
}

export enum playbackPlayMode {
    "play" = "Play",
    "playing" = "playing",
    "pause" = "pause",
    "start" = "Start",
    "stop" = "Stop",
    "restart" = "Restart",
    "ended" = "Ended",
    "resume" = "Resume",
    "forward" = "Forward",
    "rewind" = "Rewind",
    "buffering" = "Buffering",
}

export enum VideoState {
    "Mounted" = "Mounted",
    "UnMounted" = "UnMounted",
}

export const monthNames = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
];

export const NavigationTarget = {
    SHOW_FEED_ALWAYS: "Always",
    CLIENT_DEFINED: "ClientDefined",
};



export const iso639LangaugeCodeMapping: { [key: string]: string } = {
    aar: "Afar",
    aa: "Afar",
    abk: "Abkhazian",
    ab: "Abkhazian",
    ace: "Achinese",
    ach: "Acoli",
    ada: "Adangme",
    ady: "Adygei",
    afa: "Afro-Asiatic Languages",
    afh: "Afrihili",
    afr: "Afrikaans",
    af: "Afrikaans",
    ain: "Ainu",
    aka: "Akan",
    ak: "Akan",
    akk: "Akkadian",
    alb: "Albanian",
    sqi: "Albanian",
    sq: "Albanian",
    ale: "Aleut",
    alg: "Algonquian Languages",
    alt: "Southern Altai",
    amh: "Amharic",
    am: "Amharic",
    ang: "English Old (ca.450-1100)",
    anp: "Angika",
    apa: "Apache Languages",
    ara: "Arabic",
    ar: "Arabic",
    arc: "Imperial Aramaic (700-300 BCE)",
    arg: "Aragonese",
    an: "Aragonese",
    arm: "Armenian",
    hye: "Armenian",
    hy: "Armenian",
    arn: "Mapuche",
    arp: "Arapaho",
    art: "Artificial Languages",
    arw: "Arawak",
    asm: "Assamese",
    as: "Assamese",
    ast: "Asturian",
    ath: "Athapascan Languages",
    aus: "Australian Languages",
    ava: "Avaric",
    av: "Avaric",
    ave: "Avestan",
    ae: "Avestan",
    awa: "Awadhi",
    aym: "Aymara",
    ay: "Aymara",
    aze: "Azerbaijani",
    az: "Azerbaijani",
    bad: "Banda Languages",
    bai: "Bamileke Languages",
    bak: "Bashkir",
    ba: "Bashkir",
    bal: "Baluchi",
    bam: "Bambara",
    bm: "Bambara",
    ban: "Balinese",
    baq: "Basque",
    eus: "Basque",
    eu: "Basque",
    bas: "Basa",
    bat: "Baltic Languages",
    bej: "Bedawiyet",
    bel: "Belarusian",
    be: "Belarusian",
    bem: "Bemba",
    ben: "Bengali",
    bn: "Bengali",
    ber: "Berber Languages",
    bho: "Bhojpuri",
    bih: "Bihari Languages",
    bh: "Bihari Languages",
    bik: "Bikol",
    bin: "Bini",
    bis: "Bislama",
    bi: "Bislama",
    bla: "Siksika",
    bnt: "Bantu (Other)",
    bos: "Bosnian",
    bs: "Bosnian",
    bra: "Braj",
    bre: "Breton",
    br: "Breton",
    btk: "Batak Languages",
    bua: "Buriat",
    bug: "Buginese",
    bul: "Bulgarian",
    bg: "Bulgarian",
    bur: "Burmese",
    mya: "Burmese",
    my: "Burmese",
    byn: "Bilin",
    cad: "Caddo",
    cai: "Central American Indian Languages",
    car: "Galibi Carib",
    cat: "Catalan",
    ca: "Catalan",
    cau: "Caucasian Languages",
    ceb: "Cebuano",
    cel: "Celtic Languages",
    cha: "Chamorro",
    ch: "Chamorro",
    chb: "Chibcha",
    che: "Chechen",
    ce: "Chechen",
    chg: "Chagatai",
    chi: "Chinese",
    zho: "Chinese",
    zh: "Chinese",
    chk: "Chuukese",
    chm: "Mari",
    chn: "Chinook Jargon",
    cho: "Choctaw",
    chp: "Chipewyan",
    chr: "Cherokee",
    chu: "Church Slavic",
    cu: "Church Slavic",
    chv: "Chuvash",
    cv: "Chuvash",
    chy: "Cheyenne",
    cmc: "Chamic Languages",
    cop: "Coptic",
    cor: "Cornish",
    kw: "Cornish",
    cos: "Corsican",
    co: "Corsican",
    cpe: "Creoles And Pidgins",
    cpf: "Creoles And Pidgins",
    cpp: "Creoles And Pidgins",
    cre: "Cree",
    cr: "Cree",
    crh: "Crimean Tatar",
    crp: "Creoles And Pidgins",
    csb: "Kashubian",
    cus: "Cushitic Languages",
    cze: "Czech",
    ces: "Czech",
    cs: "Czech",
    dak: "Dakota",
    dan: "Danish",
    da: "Danish",
    dar: "Dargwa",
    day: "Land Dayak Languages",
    del: "Delaware",
    den: "Slave (Athapascan)",
    dgr: "Dogrib",
    din: "Dinka",
    div: "Dhivehi",
    dv: "Dhivehi",
    doi: "Dogri",
    dra: "Dravidian Languages",
    dsb: "Lower Sorbian",
    dua: "Duala",
    dum: "Dutch Middle (ca.1050-1350)",
    dut: "Dutch",
    nld: "Dutch",
    nl: "Dutch",
    dyu: "Dyula",
    dzo: "Dzongkha",
    dz: "Dzongkha",
    efi: "Efik",
    egy: "Egyptian (Ancient)",
    eka: "Ekajuk",
    elx: "Elamite",
    eng: "English",
    en: "English",
    enm: "English Middle (1100-1500)",
    epo: "Esperanto",
    eo: "Esperanto",
    est: "Estonian",
    et: "Estonian",
    ewe: "Ewe",
    ee: "Ewe",
    ewo: "Ewondo",
    fan: "Fang",
    fao: "Faroese",
    fo: "Faroese",
    fat: "Fanti",
    fij: "Fijian",
    fj: "Fijian",
    fil: "Filipino",
    fin: "Finnish",
    fi: "Finnish",
    fiu: "Finno-Ugrian Languages",
    fon: "Fon",
    fre: "French",
    fra: "French",
    fr: "French",
    frm: "French Middle (ca.1400-1600)",
    fro: "French Old (842-ca.1400)",
    frr: "Northern Frisian",
    frs: "Eastern Frisian",
    fry: "Western Frisian",
    fy: "Western Frisian",
    ful: "Fulah",
    ff: "Fulah",
    fur: "Friulian",
    gaa: "Ga",
    gay: "Gayo",
    gba: "Gbaya",
    gem: "Germanic Languages",
    geo: "Georgian",
    kat: "Georgian",
    ka: "Georgian",
    ger: "German",
    deu: "German",
    de: "German",
    gez: "Geez",
    gil: "Gilbertese",
    gla: "Gaelic",
    gd: "Gaelic",
    gle: "Irish",
    ga: "Irish",
    glg: "Galician",
    gl: "Galician",
    glv: "Manx",
    gv: "Manx",
    gmh: "German Middle High (ca.1050-1500)",
    goh: "German Old High (ca.750-1050)",
    gon: "Gondi",
    gor: "Gorontalo",
    got: "Gothic",
    grb: "Grebo",
    grc: "Greek Ancient (to 1453)",
    gre: "Greek Modern (1453-)",
    ell: "Greek Modern (1453-)",
    el: "Greek Modern (1453-)",
    grn: "Guarani",
    gn: "Guarani",
    gsw: "Alemannic",
    guj: "Gujarati",
    gu: "Gujarati",
    gwi: "Gwich'in",
    hai: "Haida",
    hat: "Haitian",
    ht: "Haitian",
    hau: "Hausa",
    ha: "Hausa",
    haw: "Hawaiian",
    heb: "Hebrew",
    he: "Hebrew",
    her: "Herero",
    hz: "Herero",
    hil: "Hiligaynon",
    him: "Himachali Languages",
    hin: "Hindi",
    hi: "Hindi",
    hit: "Hittite",
    hmn: "Hmong",
    hmo: "Hiri Motu",
    ho: "Hiri Motu",
    hrv: "Croatian",
    hr: "Croatian",
    hsb: "Upper Sorbian",
    hun: "Hungarian",
    hu: "Hungarian",
    hup: "Hupa",
    iba: "Iban",
    ibo: "Igbo",
    ig: "Igbo",
    ice: "Icelandic",
    isl: "Icelandic",
    is: "Icelandic",
    ido: "Ido",
    io: "Ido",
    iii: "Nuosu",
    ii: "Nuosu",
    ijo: "Ijo Languages",
    iku: "Inuktitut",
    iu: "Inuktitut",
    ile: "Interlingue",
    ie: "Interlingue",
    ilo: "Iloko",
    ina: "Interlingua (International Auxiliary Language Association)",
    ia: "Interlingua (International Auxiliary Language Association)",
    inc: "Indic Languages",
    ind: "Indonesian",
    id: "Indonesian",
    ine: "Indo-European Languages",
    inh: "Ingush",
    ipk: "Inupiaq",
    ik: "Inupiaq",
    ira: "Iranian Languages",
    iro: "Iroquoian Languages",
    ita: "Italian",
    it: "Italian",
    jav: "Javanese",
    jv: "Javanese",
    jbo: "Lojban",
    jpn: "Japanese",
    ja: "Japanese",
    jpr: "Judeo-Persian",
    jrb: "Judeo-Arabic",
    kaa: "Kara-Kalpak",
    kab: "Kabyle",
    kac: "Jingpho",
    kal: "Greenlandic",
    kl: "Greenlandic",
    kam: "Kamba",
    kan: "Kannada",
    kn: "Kannada",
    kar: "Karen Languages",
    kas: "Kashmiri",
    ks: "Kashmiri",
    kau: "Kanuri",
    kr: "Kanuri",
    kaw: "Kawi",
    kaz: "Kazakh",
    kk: "Kazakh",
    kbd: "Kabardian",
    kha: "Khasi",
    khi: "Khoisan Languages",
    khm: "Central Khmer",
    km: "Central Khmer",
    kho: "Khotanese",
    kik: "Gikuyu",
    ki: "Gikuyu",
    kin: "Kinyarwanda",
    rw: "Kinyarwanda",
    kir: "Kirghiz",
    ky: "Kirghiz",
    kmb: "Kimbundu",
    kok: "Konkani",
    kom: "Komi",
    kv: "Komi",
    kon: "Kongo",
    kg: "Kongo",
    kor: "Korean",
    ko: "Korean",
    kos: "Kosraean",
    kpe: "Kpelle",
    krc: "Karachay-Balkar",
    krl: "Karelian",
    kro: "Kru Languages",
    kru: "Kurukh",
    kua: "Kuanyama",
    kj: "Kuanyama",
    kum: "Kumyk",
    kur: "Kurdish",
    ku: "Kurdish",
    kut: "Kutenai",
    lad: "Ladino",
    lah: "Lahnda",
    lam: "Lamba",
    lao: "Lao",
    lo: "Lao",
    lat: "Latin",
    la: "Latin",
    lav: "Latvian",
    lv: "Latvian",
    lez: "Lezghian",
    lim: "Limburgan",
    li: "Limburgan",
    lin: "Lingala",
    ln: "Lingala",
    lit: "Lithuanian",
    lt: "Lithuanian",
    lol: "Mongo",
    loz: "Lozi",
    ltz: "Letzeburgesch",
    lb: "Letzeburgesch",
    lua: "Luba-Lulua",
    lub: "Luba-Katanga",
    lu: "Luba-Katanga",
    lug: "Ganda",
    lg: "Ganda",
    lui: "Luiseno",
    lun: "Lunda",
    luo: "Luo (Kenya And Tanzania)",
    lus: "Lushai",
    mac: "Macedonian",
    mkd: "Macedonian",
    mk: "Macedonian",
    mad: "Madurese",
    mag: "Magahi",
    mah: "Marshallese",
    mh: "Marshallese",
    mai: "Maithili",
    mak: "Makasar",
    mal: "Malayalam",
    ml: "Malayalam",
    man: "Mandingo",
    mao: "Maori",
    mri: "Maori",
    mi: "Maori",
    map: "Austronesian Languages",
    mar: "Marathi",
    mr: "Marathi",
    mas: "Masai",
    may: "Malay",
    msa: "Malay",
    ms: "Malay",
    mdf: "Moksha",
    mdr: "Mandar",
    men: "Mende",
    mga: "Irish Middle (900-1200)",
    mic: "Mi'kmaq",
    min: "Minangkabau",
    mis: "Uncoded Languages",
    mkh: "Mon-Khmer Languages",
    mlg: "Malagasy",
    mg: "Malagasy",
    mlt: "Maltese",
    mt: "Maltese",
    mnc: "Manchu",
    mni: "Manipuri",
    mno: "Manobo Languages",
    moh: "Mohawk",
    mon: "Mongolian",
    mn: "Mongolian",
    mos: "Mossi",
    mul: "Multiple Languages",
    mun: "Munda Languages",
    mus: "Creek",
    mwl: "Mirandese",
    mwr: "Marwari",
    myn: "Mayan Languages",
    myv: "Erzya",
    nah: "Nahuatl Languages",
    nai: "North American Indian Languages",
    nap: "Neapolitan",
    nau: "Nauru",
    na: "Nauru",
    nav: "Navaho",
    nv: "Navaho",
    nbl: "Ndebele",
    nr: "Ndebele",
    nde: "Ndebele",
    nd: "Ndebele",
    ndo: "Ndonga",
    ng: "Ndonga",
    nds: "Low",
    nep: "Nepali",
    ne: "Nepali",
    new: "Nepal Bhasa",
    nia: "Nias",
    nic: "Niger-Kordofanian Languages",
    niu: "Niuean",
    nno: "Norwegian",
    nn: "Norwegian",
    nob: "Bokm\u00e5l",
    nb: "Bokm\u00e5l",
    nog: "Nogai",
    non: "Norse",
    nor: "Norwegian",
    no: "Norwegian",
    nqo: "N'Ko",
    nso: "Northern Sotho",
    nub: "Nubian Languages",
    nwc: "Classical Nepal Bhasa",
    nya: "Chewa",
    ny: "Chewa",
    nym: "Nyamwezi",
    nyn: "Nyankole",
    nyo: "Nyoro",
    nzi: "Nzima",
    oci: "Occitan (post 1500)",
    oc: "Occitan (post 1500)",
    oji: "Ojibwa",
    oj: "Ojibwa",
    ori: "Oriya",
    or: "Oriya",
    orm: "Oromo",
    om: "Oromo",
    osa: "Osage",
    oss: "Ossetian",
    os: "Ossetian",
    ota: "Turkish Ottoman (1500-1928)",
    oto: "Otomian Languages",
    paa: "Papuan Languages",
    pag: "Pangasinan",
    pal: "Pahlavi",
    pam: "Kapampangan",
    pan: "Panjabi",
    pa: "Panjabi",
    pap: "Papiamento",
    pau: "Palauan",
    peo: "Persian Old (ca.600-400 B.C.)",
    per: "Persian",
    fas: "Persian",
    fa: "Persian",
    phi: "Philippine Languages",
    phn: "Phoenician",
    pli: "Pali",
    pi: "Pali",
    pol: "Polish",
    pl: "Polish",
    pon: "Pohnpeian",
    por: "Portuguese",
    pt: "Portuguese",
    pra: "Prakrit Languages",
    pro: "Proven\u00e7al Old (to 1500)",
    pus: "Pashto",
    ps: "Pashto",
    "qaa-qtz": "Reserved For Local Use",
    que: "Quechua",
    qu: "Quechua",
    raj: "Rajasthani",
    rap: "Rapanui",
    rar: "Cook Islands Maori",
    roa: "Romance Languages",
    roh: "Romansh",
    rm: "Romansh",
    rom: "Romany",
    rum: "Moldavian",
    ron: "Moldavian",
    ro: "Moldavian",
    run: "Rundi",
    rn: "Rundi",
    rup: "Aromanian",
    rus: "Russian",
    ru: "Russian",
    sad: "Sandawe",
    sag: "Sango",
    sg: "Sango",
    sah: "Yakut",
    sai: "South American Indian (Other)",
    sal: "Salishan Languages",
    sam: "Samaritan Aramaic",
    san: "Sanskrit",
    sa: "Sanskrit",
    sas: "Sasak",
    sat: "Santali",
    scn: "Sicilian",
    sco: "Scots",
    sel: "Selkup",
    sem: "Semitic Languages",
    sga: "Irish Old (to 900)",
    sgn: "Sign Languages",
    shn: "Shan",
    sid: "Sidamo",
    sin: "Sinhala",
    si: "Sinhala",
    sio: "Siouan Languages",
    sit: "Sino-Tibetan Languages",
    sla: "Slavic Languages",
    slo: "Slovak",
    slk: "Slovak",
    sk: "Slovak",
    slv: "Slovenian",
    sl: "Slovenian",
    sma: "Southern Sami",
    sme: "Northern Sami",
    se: "Northern Sami",
    smi: "Sami Languages",
    smj: "Lule Sami",
    smn: "Inari Sami",
    smo: "Samoan",
    sm: "Samoan",
    sms: "Skolt Sami",
    sna: "Shona",
    sn: "Shona",
    snd: "Sindhi",
    sd: "Sindhi",
    snk: "Soninke",
    sog: "Sogdian",
    som: "Somali",
    so: "Somali",
    son: "Songhai Languages",
    sot: "Sotho",
    st: "Sotho",
    spa: "Castilian",
    es: "Castilian",
    srd: "Sardinian",
    sc: "Sardinian",
    srn: "Sranan Tongo",
    srp: "Serbian",
    sr: "Serbian",
    srr: "Serer",
    ssa: "Nilo-Saharan Languages",
    ssw: "Swati",
    ss: "Swati",
    suk: "Sukuma",
    sun: "Sundanese",
    su: "Sundanese",
    sus: "Susu",
    sux: "Sumerian",
    swa: "Swahili",
    sw: "Swahili",
    swe: "Swedish",
    sv: "Swedish",
    syc: "Classical Syriac",
    syr: "Syriac",
    tah: "Tahitian",
    ty: "Tahitian",
    tai: "Tai Languages",
    tam: "Tamil",
    ta: "Tamil",
    tat: "Tatar",
    tt: "Tatar",
    tel: "Telugu",
    te: "Telugu",
    tem: "Timne",
    ter: "Tereno",
    tet: "Tetum",
    tgk: "Tajik",
    tg: "Tajik",
    tgl: "Tagalog",
    tl: "Tagalog",
    tha: "Thai",
    th: "Thai",
    tib: "Tibetan",
    bod: "Tibetan",
    bo: "Tibetan",
    tig: "Tigre",
    tir: "Tigrinya",
    ti: "Tigrinya",
    tiv: "Tiv",
    tkl: "Tokelau",
    tlh: "Klingon",
    tli: "Tlingit",
    tmh: "Tamashek",
    tog: "Tonga (Nyasa)",
    ton: "Tonga (Tonga Islands)",
    to: "Tonga (Tonga Islands)",
    tpi: "Tok Pisin",
    tsi: "Tsimshian",
    tsn: "Tswana",
    tn: "Tswana",
    tso: "Tsonga",
    ts: "Tsonga",
    tuk: "Turkmen",
    tk: "Turkmen",
    tum: "Tumbuka",
    tup: "Tupi Languages",
    tur: "Turkish",
    tr: "Turkish",
    tut: "Altaic Languages",
    tvl: "Tuvalu",
    twi: "Twi",
    tw: "Twi",
    tyv: "Tuvinian",
    udm: "Udmurt",
    uga: "Ugaritic",
    uig: "Uighur",
    ug: "Uighur",
    ukr: "Ukrainian",
    uk: "Ukrainian",
    umb: "Umbundu",
    und: "Undetermined",
    urd: "Urdu",
    ur: "Urdu",
    uzb: "Uzbek",
    uz: "Uzbek",
    vai: "Vai",
    ven: "Venda",
    ve: "Venda",
    vie: "Vietnamese",
    vi: "Vietnamese",
    vol: "Volap\u00fck",
    vo: "Volap\u00fck",
    vot: "Votic",
    wak: "Wakashan Languages",
    wal: "Walamo",
    war: "Waray",
    was: "Washo",
    wel: "Welsh",
    cym: "Welsh",
    cy: "Welsh",
    wen: "Sorbian Languages",
    wln: "Walloon",
    wa: "Walloon",
    wol: "Wolof",
    wo: "Wolof",
    xal: "Kalmyk",
    xho: "Xhosa",
    xh: "Xhosa",
    yao: "Yao",
    yap: "Yapese",
    yid: "Yiddish",
    yi: "Yiddish",
    yor: "Yoruba",
    yo: "Yoruba",
    ypk: "Yupik Languages",
    zap: "Zapotec",
    zbl: "Bliss",
    zen: "Zenaga",
    zgh: "Standard Moroccan Tamazight",
    zha: "Chuang",
    za: "Chuang",
    znd: "Zande Languages",
    zul: "Zulu",
    zu: "Zulu",
    zun: "Zuni",
    zxx: "No Linguistic Content",
    zza: "Dimili",
};

export const galleryFilterListKey = [
    "SortBy",
    "ShowType",
    "Genre",
    "Language",
    "LicenseWindow",
    "Price",
    "QualityLevel",
    "Restrictions",
    "FilterBy",
    "Category",
    "TimeFrame",
    "OfferType",
    "Subscribed",
];

export enum FeedType {
    Dynamic = "Dynamic",
    Custom = "Custom",
    Mixed = "Mixed",
}

export const Genre: { [key: string]: string } = {
    "2001": "ActionAdventure",
    "2002": "Adults Only",
    "2003": "Family",
    "2004": "News",
    "2005": "Sports",
    "2681": "Comedy",
    "2715": "Drama",
    "2729": "Fantasy",
    "2771": "Horror",
    "2821": "Musical",
    "2822": "Mystery",
    "2880": "Romance",
    "2888": "Sci-Fi",
    "2921": "Thriller",
    "2013": "Western",
    "2014": "Cooking",
    "2015": "Education",
    "2913": "Game show",
    "2017": "How-to",
    "2018": "Music",
    "2019": "Reality",
    "2020": "Soap opera",
    "2021": "Talk show",
    "2022": "Travel",
    "2023": "Other",
    "2300": "Movie",
};

export enum RecorderModel {
    Private = "Private",
    Shared = "Shared",
    Local = "Local",
}

export enum DvrRecordedState {
    Canceled = "Canceled",
    Scheduled = "Scheduled",
    Recorded = "Recorded",
    Recording = "Recording",
    Conflicts = "Conflicts",
}

export const DVRAnyTimeAnyChannel = "AnyTimeAnyChannel";

export const separator = "  ·  ";

export enum PinType {
    adult = "adult",
    content = "parentalcontrol",
    purchase = "purchase",
}

export const profileEditButtonFontSize = { fontSize: 70 };

export const addUserIcon = "res://drawable/default/add-user.png";

export const sortyByDateFilterState = "SortBy|Date";

export const orderByDateFilterState = "orderBy|Date";

export enum ItemShowType {
    "Program" = "Program",
    "SingleProgram" = "SingleProgram",
    "TVShow" = "TVShow",
    "Series" = "Series",
    "Movie" = "Movie",
    "MovieAndTVShow" = "MovieAndTVShow",
    "SvodPackage" = "SvodPackage",
    "browseSvodPackage" = "browseSvodPackage",
    "liveTvGuide" = "liveTvGuide",
    "DvrScheduled" = "DvrScheduled",
    "DvrRecording" = "DvrRecording",
    "DvrProgram" = "DvrProgram",
    "DvrMovie" = "DvrMovie",
    "Package" = "Package",
    "discovery" = "discovery",
    "subscriber" = "subscriber",
    "Person" = "Person",
    "App" = "App",
    "Title" = "Title",
    "Episode" = "Episode",
    "Channel" = "Channel",
    "FavoriteChannel" = "FavoriteChannel",
    "Catchup" = "catchup",
    "GenericProgram" = "GenericProgram",
}

export enum Layout {
    "Category" = "Category",
    "Gallery" = "Gallery",
}

export enum RecordStatus {
    "RECORDING" = "RECORDING",
    "SCHEDULED" = "SCHEDULED",
}

export enum catchupMode {
    "Dvr" = "Dvr",
    "RollingBuffer" = "RollingBuffer",
    "RollingBufferKeepDvr" = "RollingBufferKeepDvr",
}

export enum PlaybackTerminationEvent {
    "Stopped" = "Stopped",
    "Completed" = "Completed",
    "Failed" = "Failed",
    "ProgramBoundaryCrossed" = "ProgramBoundaryCrossed",
    "AppGoesInBackground" = "AppGoesInBackground",
}

export enum PlaybackType {
    "VOD" = "VOD",
    "LiveTV" = "LiveTV",
    "LiveTVCatchup" = "LiveTVCatchup",
    "NetworkRecording" = "NetworkRecording",
}

export enum ServiceGroupType {
    TRAILER = 0,
    PPV = 1,
}

export const navigationAction = {
    pageOpen: "Open",
    pageClose: "Close",
};

export const routeHistory = {
    currentRoute: 1,
    previousRoute: 2,
};

export const EXITTIME = 1500;
