#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef BITMOVINANALYTICSCOLLECTOR_SWIFT_H
#define BITMOVINANALYTICSCOLLECTOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import BitmovinPlayer;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BitmovinAnalyticsCollector",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector17BitmovinAdAdapter")
@interface BitmovinAdAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BMPAdManifestLoadedEvent;
@protocol BMPPlayer;
@class BMPAdStartedEvent;
@class BMPAdFinishedEvent;
@class BMPAdBreakStartedEvent;
@class BMPAdBreakFinishedEvent;
@class BMPAdClickedEvent;
@class BMPAdSkippedEvent;
@class BMPAdErrorEvent;
@class BMPAdQuartileEvent;

@interface BitmovinAdAdapter (SWIFT_EXTENSION(BitmovinAnalyticsCollector)) <BMPPlayerListener>
- (void)onAdManifestLoaded:(BMPAdManifestLoadedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdStarted:(BMPAdStartedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdFinished:(BMPAdFinishedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdBreakStarted:(BMPAdBreakStartedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdBreakFinished:(BMPAdBreakFinishedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdClicked:(BMPAdClickedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdSkipped:(BMPAdSkippedEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdError:(BMPAdErrorEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
- (void)onAdQuartile:(BMPAdQuartileEvent * _Nonnull)event player:(id <BMPPlayer> _Nonnull)player;
@end

@class BitmovinAnalyticsConfig;
@class CustomData;
@protocol BMPSource;
@class SourceMetadata;
@class NSString;

SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector23BitmovinPlayerCollector")
@interface BitmovinPlayerCollector : NSObject
- (nonnull instancetype)initWithConfig:(BitmovinAnalyticsConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
/// Attach a player instance to this analytics plugin. After this is completed, BitmovinAnalytics
/// will start monitoring and sending analytics data based on the attached player instance.
- (void)attachPlayerWithPlayer:(id <BMPPlayer> _Nonnull)player;
- (void)detachPlayer;
- (CustomData * _Nonnull)getCustomData SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomDataWithCustomData:(CustomData * _Nonnull)customData;
- (void)setCustomDataOnceWithCustomData:(CustomData * _Nonnull)customData;
- (void)addSourceMetadataWithPlayerSource:(id <BMPSource> _Nonnull)playerSource sourceMetadata:(SourceMetadata * _Nonnull)sourceMetadata;
- (NSString * _Nonnull)getUserId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector17BitmovinAnalytics")
@interface BitmovinAnalytics : BitmovinPlayerCollector
- (nonnull instancetype)initWithConfig:(BitmovinAnalyticsConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
/// Attach a player instance to this analytics plugin. After this is completed, BitmovinAnalytics
/// will start monitoring and sending analytics data based on the attached player instance.
- (void)attachBitmovinPlayerWithPlayer:(id <BMPPlayer> _Nonnull)player;
@end


SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector23BitmovinAnalyticsConfig")
@interface BitmovinAnalyticsConfig : NSObject
/// CDN Provide that the video playback session is using
@property (nonatomic, copy) NSString * _Nullable cdnProvider;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData1;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData2;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData3;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData4;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData5;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData6;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData7;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData8;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData9;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData10;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData11;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData12;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData13;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData14;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData15;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData16;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData17;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData18;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData19;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData20;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData21;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData22;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData23;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData24;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData25;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData26;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData27;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData28;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData29;
/// Optional free-form custom data
@property (nonatomic, copy) NSString * _Nullable customData30;
/// User ID of the customer
@property (nonatomic, copy) NSString * _Nullable customerUserId;
/// Experiment name needed for A/B testing
@property (nonatomic, copy) NSString * _Nullable experimentName;
/// ID of the video in the CMS system
@property (nonatomic, copy) NSString * _Nullable videoId;
/// Human readable title of the video asset currently playing
@property (nonatomic, copy) NSString * _Nullable title;
/// Analytics key. Find this value on dashboard.bitmovin.com/analytics
@property (nonatomic, copy) NSString * _Nonnull key;
/// Player key. Find this value on dashboard.bitmovin.com/analytics
@property (nonatomic, copy) NSString * _Nonnull playerKey;
/// Breadcrumb path to show where in the app the user is
@property (nonatomic, copy) NSString * _Nullable path;
/// Flag to see if stream is live before stream metadata is available (default: false)
@property (nonatomic) BOOL isLive;
/// Flag to enable Ad tracking
@property (nonatomic) BOOL ads;
/// How often the video engine should heartbeat
@property (nonatomic) NSInteger heartbeatInterval SWIFT_DEPRECATED_MSG("No longer possible to change default value of 59700ms");
/// Flag to use randomised userId not depending on device specific values
@property (nonatomic) BOOL randomizeUserId;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key playerKey:(NSString * _Nonnull)playerKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// An iOS analytics plugin that sends video playback analytics to Bitmovin Analytics servers. Currently
/// supports analytics on AVPlayer video players
SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector25BitmovinAnalyticsInternal")
@interface BitmovinAnalyticsInternal : NSObject
/// Detach the current player that is being used with Bitmovin Analytics.
- (void)detachPlayer;
- (CustomData * _Nonnull)getCustomData SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomDataWithCustomData:(CustomData * _Nonnull)customData;
- (void)setCustomDataOnceWithCustomData:(CustomData * _Nonnull)customData;
- (NSString * _Nonnull)getUserId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector17CorePlayerAdapter")
@interface CorePlayerAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector10CustomData")
@interface CustomData : NSObject
@property (nonatomic, copy) NSString * _Nullable customData1;
@property (nonatomic, copy) NSString * _Nullable customData2;
@property (nonatomic, copy) NSString * _Nullable customData3;
@property (nonatomic, copy) NSString * _Nullable customData4;
@property (nonatomic, copy) NSString * _Nullable customData5;
@property (nonatomic, copy) NSString * _Nullable customData6;
@property (nonatomic, copy) NSString * _Nullable customData7;
@property (nonatomic, copy) NSString * _Nullable customData8;
@property (nonatomic, copy) NSString * _Nullable customData9;
@property (nonatomic, copy) NSString * _Nullable customData10;
@property (nonatomic, copy) NSString * _Nullable customData11;
@property (nonatomic, copy) NSString * _Nullable customData12;
@property (nonatomic, copy) NSString * _Nullable customData13;
@property (nonatomic, copy) NSString * _Nullable customData14;
@property (nonatomic, copy) NSString * _Nullable customData15;
@property (nonatomic, copy) NSString * _Nullable customData16;
@property (nonatomic, copy) NSString * _Nullable customData17;
@property (nonatomic, copy) NSString * _Nullable customData18;
@property (nonatomic, copy) NSString * _Nullable customData19;
@property (nonatomic, copy) NSString * _Nullable customData20;
@property (nonatomic, copy) NSString * _Nullable customData21;
@property (nonatomic, copy) NSString * _Nullable customData22;
@property (nonatomic, copy) NSString * _Nullable customData23;
@property (nonatomic, copy) NSString * _Nullable customData24;
@property (nonatomic, copy) NSString * _Nullable customData25;
@property (nonatomic, copy) NSString * _Nullable customData26;
@property (nonatomic, copy) NSString * _Nullable customData27;
@property (nonatomic, copy) NSString * _Nullable customData28;
@property (nonatomic, copy) NSString * _Nullable customData29;
@property (nonatomic, copy) NSString * _Nullable customData30;
@property (nonatomic, copy) NSString * _Nullable experimentName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC26BitmovinAnalyticsCollector14SourceMetadata")
@interface SourceMetadata : NSObject
- (nonnull instancetype)initWithVideoId:(NSString * _Nullable)videoId title:(NSString * _Nullable)title path:(NSString * _Nullable)path isLive:(BOOL)isLive cdnProvider:(NSString * _Nullable)cdnProvider customData1:(NSString * _Nullable)customData1 customData2:(NSString * _Nullable)customData2 customData3:(NSString * _Nullable)customData3 customData4:(NSString * _Nullable)customData4 customData5:(NSString * _Nullable)customData5 customData6:(NSString * _Nullable)customData6 customData7:(NSString * _Nullable)customData7 customData8:(NSString * _Nullable)customData8 customData9:(NSString * _Nullable)customData9 customData10:(NSString * _Nullable)customData10 customData11:(NSString * _Nullable)customData11 customData12:(NSString * _Nullable)customData12 customData13:(NSString * _Nullable)customData13 customData14:(NSString * _Nullable)customData14 customData15:(NSString * _Nullable)customData15 customData16:(NSString * _Nullable)customData16 customData17:(NSString * _Nullable)customData17 customData18:(NSString * _Nullable)customData18 customData19:(NSString * _Nullable)customData19 customData20:(NSString * _Nullable)customData20 customData21:(NSString * _Nullable)customData21 customData22:(NSString * _Nullable)customData22 customData23:(NSString * _Nullable)customData23 customData24:(NSString * _Nullable)customData24 customData25:(NSString * _Nullable)customData25 customData26:(NSString * _Nullable)customData26 customData27:(NSString * _Nullable)customData27 customData28:(NSString * _Nullable)customData28 customData29:(NSString * _Nullable)customData29 customData30:(NSString * _Nullable)customData30 experimentName:(NSString * _Nullable)experimentName OBJC_DESIGNATED_INITIALIZER;
/// ID of the video in the CMS system
@property (nonatomic, readonly, copy) NSString * _Nullable videoId;
/// Human readable title of the video asset currently playing
@property (nonatomic, readonly, copy) NSString * _Nullable title;
/// Breadcrumb path to show where in the app the user is
@property (nonatomic, readonly, copy) NSString * _Nullable path;
/// Flag to see if stream is live before stream metadata is available
@property (nonatomic, readonly) BOOL isLive;
/// CDN Provide that the video playback session is using
@property (nonatomic, readonly, copy) NSString * _Nullable cdnProvider;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData1;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData2;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData3;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData4;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData5;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData6;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData7;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData8;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData9;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData10;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData11;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData12;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData13;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData14;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData15;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData16;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData17;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData18;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData19;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData20;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData21;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData22;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData23;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData24;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData25;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData26;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData27;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData28;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData29;
/// Optional free-form custom data
@property (nonatomic, readonly, copy) NSString * _Nullable customData30;
/// Experiment name needed for A/B testing
@property (nonatomic, readonly, copy) NSString * _Nullable experimentName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
